openapi: 3.0.0
info:
  title: Catalog Status
  description: ONDC Network BAPs catalog status API model implementation
  version: 1.2.0
security:
  - SubscriberAuth: []
paths:
  /<bap_catalog_status_uri>:
    post:
      tags:
        - Consumer Platform (BAP)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                context:
                  $ref: '#/components/schemas/Context'
                message:
                  type: object
                  properties:
                    catalog:
                      $ref: '#/components/schemas/Catalog'
            example:
              context:
                country: IND
                domain: ONDC:RET10
                timestamp: '2023-09-26T23:04:05.254Z'
                action: on_search
                bap_id: example-test-bap.com
                bpp_id: example-test-bpp.com
                transaction_id: T1
                message_id: M1
                city: 'std:080'
                core_version: 1.2.0
      responses:
        default:
          description: Response received
          content:
            application/json:
              schema:
                type: object
                properties:
                  context:
                    $ref: '#/components/schemas/Context'
                  message:
                    type: object
                    properties:
                      catalog:
                        $ref: '#/components/schemas/Catalog'
                required:
                  - context
                  - message
                example:
                  context:
                    country: IND
                    domain: ONDC:RET10
                    timestamp: '2023-09-26T23:04:05.254Z'
                    action: on_search
                    bap_id: example-test-bap.com
                    bpp_id: example-test-bpp.com
                    transaction_id: T1
                    message_id: M1
                    city: 'std:080'
                    core_version: 1.2.0
                  message:
                    catalog:
                      status:
                        code: IN_PROGRESS
                        updated_at: '2023-09-26T23:04:02.254Z'
        x-response-in-progress:
          description: Response received
          content:
            application/json:
              schema:
                type: object
                properties:
                  context:
                    $ref: '#/components/schemas/Context'
                  message:
                    type: object
                    properties:
                      catalog:
                        $ref: '#/components/schemas/Catalog'
                required:
                  - context
                  - message
                example:
                  context:
                    country: IND
                    domain: ONDC:RET10
                    timestamp: '2023-09-26T23:04:05.254Z'
                    action: on_search
                    bap_id: example-test-bap.com
                    bpp_id: example-test-bpp.com
                    transaction_id: T1
                    message_id: M1
                    city: 'std:080'
                    core_version: 1.2.0
                  message:
                    catalog:
                      status:
                        code: IN_PROGRESS
                        updated_at: '2023-09-26T23:04:02.254Z'
                      tags:
                        code: CATALOG_PROCESSING
                        list:
                        - code: MIN_PROCESS_DURATION
                          value: PT1H
        x-response-expired:
          description: Response received
          content:
            application/json:
              schema:
                type: object
                properties:
                  context:
                    $ref: '#/components/schemas/Context'
                  message:
                    type: object
                    properties:
                      catalog:
                        $ref: '#/components/schemas/Catalog'
                required:
                  - context
                  - message
                example:
                  context:
                    country: IND
                    domain: ONDC:RET10
                    timestamp: '2023-09-26T23:04:05.254Z'
                    action: on_search
                    bap_id: example-test-bap.com
                    bpp_id: example-test-bpp.com
                    transaction_id: T1
                    message_id: M1
                    city: 'std:080'
                    core_version: 1.2.0
                  message:
                    catalog:
                      status:
                        code: EXPIRED
                        updated_at: '2023-09-26T23:04:02.254Z'
        x-response-processed-error:
          description: Response received
          content:
            application/json:
              schema:
                type: object
                properties:
                  context:
                    $ref: '#/components/schemas/Context'
                  message:
                    type: object
                    properties:
                      catalog:
                        $ref: '#/components/schemas/Catalog'
                required:
                  - context
                  - message
                example:
                  context:
                    country: IND
                    domain: ONDC:RET10
                    timestamp: '2023-09-26T23:04:05.254Z'
                    action: on_search
                    bap_id: example-test-bap.com
                    bpp_id: example-test-bpp.com
                    transaction_id: T1
                    message_id: M1
                    city: 'std:080'
                    core_version: 1.2.0
                  message:
                    catalog:
                      status:
                        code: PROCESSED_WITH_ERRORS
                        updated_at: '2023-09-26T23:04:02.254Z'
                      bpp/providers:
                        - id: P1
                          items:
                            - id: I1
                              error:
                                code: '1001'
                                paths: descriptor.name
                                message: Element missing
                            - id: I2
                              error:
                                code: '1002'
                                paths: price.value
                                message: Invalid format
                        - id: P2
                          error:
                            code: '1003'
                            message: Fulfillment rate below 20%
        x-response-processed-success:
          description: Response received
          content:
            application/json:
              schema:
                type: object
                properties:
                  context:
                    $ref: '#/components/schemas/Context'
                  message:
                    type: object
                    properties:
                      catalog:
                        $ref: '#/components/schemas/Catalog'
                required:
                  - context
                  - message
                example:
                  context:
                    country: IND
                    domain: ONDC:RET10
                    timestamp: '2023-09-26T23:04:05.254Z'
                    action: on_search
                    bap_id: example-test-bap.com
                    bpp_id: example-test-bpp.com
                    transaction_id: T1
                    message_id: M1
                    city: 'std:080'
                    core_version: 1.2.0
                  message:
                    catalog:
                      status:
                        code: PROCESSED_SUCCESS
                        updated_at: '2023-09-26T23:04:02.254Z'
  /on_search:
    post:
      tags:
        - Consumer Platform (BAP)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                context:
                  $ref: '#/components/schemas/Context'
                message:
                  type: object
                error:
                  $ref: '#/components/schemas/Error'
              required:
                - context
              example:
                context:
                  country: IND
                  domain: ONDC:RET10
                  timestamp: '2023-09-26T23:04:05.254Z'
                  bap_id: example-test-bap.com
                  bap_uri: https://example-test-bap.com/ondc
                  bpp_id: example-test-bpp.com
                  bpp_uri: https://example-test-bpp.com/ondc
                  action: on_search
                  transaction_id: T1
                  message_id: M1
                  city: 'std:080'
                  core_version: 1.2.0
                  ttl: PT30S
                message:
                  catalog: '{ BPP Catalog }'
      responses:
        default:
          description: Response received
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    properties:
                      ack:
                        $ref: '#/components/schemas/Ack'
                  error:
                    $ref: '#/components/schemas/Error'
                  tags:
                    $ref: '#/components/schemas/TagGroup'
                required:
                  - message
                example:
                  message:
                    ack:
                      status: ACK
                    tags:
                      code: CATALOG_PROCESSING
                      list:
                        - code: STATUS_CHECK_URI
                          value: https://example-test-bap.com/ondc/<bap_catalog_status_uri>
                        - code: MIN_PROCESS_DURATION
                          value: PT1H
components:
  securitySchemes:
    SubscriberAuth:
      type: apiKey
      in: header
      name: Authorization
      description: 'Signature of message body using BAP or BPP subscriber''s signing public key. <br/><br/>Format:<br/><br/><code>Authorization : Signature keyId="{subscriber_id}|{unique_key_id}|{algorithm}",algorithm="ed25519",created="1606970629",expires="1607030629",headers="(created) (expires) digest",signature="Base64(signing string)"</code>'
  schemas:
    Ack:
      type: object
      properties:
        status:
          type: string
          enum:
            - ACK
            - NACK
        tags:
          type: array
          items:
            $ref: '#/components/schemas/TagGroup'
    Context:
      type: object
      properties:
        domain:
          type: string
        country:
          type: string
        city:
          type: string
        action:
          type: string
        core_version:
          type: string
        bap_id:
          type: string
        bap_uri:
          type: string
        bpp_id:
          type: string
        bpp_uri:
          type: string
        transaction_id:
          type: string
        message_id:
          type: string
        timestamp:
          type: string
        key:
          type: string
        ttl:
          type: string
    Catalog:
      type: object
      properties:
        bpp/providers:
          type: array
          items:
            $ref: '#/components/schemas/Provider'
        status:
          $ref: '#/components/schemas/Status'
    Error:
      type: object
      properties:
        code:
          type: string
        paths:
          type: string
        message:
          type: string
    Item:
      type: object
      properties:
        id:
          type: string
        error:
          $ref: '#/components/schemas/Error'
    Provider:
      type: object
      properties:
        id:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
        error:
          $ref: '#/components/schemas/Error'
    Status:
      description: Describes a state
      type: object
      properties:
        code:
          type: string
        updated_at:
          type: string
          format: date-time
    Tag:
      type: object
      properties:
        code:
          type: string
        value:
          type: string
    TagGroup:
      type: object
      properties:
        code:
          type: string
        list:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/shreyansh.shah4/Catalog-Status-API/1.2.0